apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-consumers
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-consumers
  template:
    metadata:
      labels:
        app: multi-consumers
    spec:
      containers:
      - name: multi-consumers
        image: iamokjin/news-consumer:latest
        env:
        - name: TZ
          value: "Asia/Seoul"
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "antigravity"
        - name: DB_NAME
          value: "kafka_logs"
        volumeMounts:
        - name: consumer-logs
          mountPath: /app/logs
      volumes:
      - name: consumer-logs
        emptyDir: {} # Or use a PVC if logs need to be persisted
