apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-consumer-redis
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-consumer-redis
  template:
    metadata:
      labels:
        app: news-consumer-redis
    spec:
      containers:
        - name: news-consumer-redis
          image: iamokjin/news-consumer-redis:latest
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: KAFKA_BROKERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: KAFKA_TOPIC
              value: "news-topic"
            - name: REDIS_URL
              value: "redis://redis:6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-consumer-postgres
  namespace: kafka
spec:
  replicas: 5
  selector:
    matchLabels:
      app: news-consumer-postgres
  template:
    metadata:
      labels:
        app: news-consumer-postgres
    spec:
      containers:
        - name: news-consumer-postgres
          image: iamokjin/news-consumer-postgres:latest
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: KAFKA_BROKERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: KAFKA_TOPIC
              value: "news-topic"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "antigravity"
            - name: DB_NAME
              value: "kafka_logs"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
